import {
  UserProfile,
  Instrument,
  Application,
  Certificate,
  DeficiencyMemo,
  Jurisdiction,
  AuditLogEntry,
  RenewalAlert,
} from '@/types/metrology';

export const MOCK_JURISDICTIONS: Jurisdiction[] = [
  {
    id: 'JUR-DL-SOUTH',
    state: 'Delhi (NCT)',
    district: 'South Delhi',
    zone: 'Zone 4 - Saket / Hauz Khas',
    pinCodes: ['110016', '110017', '110019', '110020', '110029', '110048', '110070'],
    assignedLmoId: 'USR-LMO-001',
    assignedLmoName: 'Shri Rajesh Varma (LMO)',
    assignedGatcId: 'USR-GATC-001',
    assignedGatcName: 'National Metrology Testing Lab (GATC)',
    officeAddress: 'O/o Assistant Controller, Legal Metrology, District Court Complex, Saket, New Delhi - 110017',
    contactEmail: 'lmo.southdelhi@doca.gov.in',
    contactPhone: '+91-11-2956-4411',
  },
  {
    id: 'JUR-MH-MUMBAI-SUB',
    state: 'Maharashtra',
    district: 'Mumbai Suburban',
    zone: 'Andheri & BKC West',
    pinCodes: ['400050', '400051', '400053', '400058', '400069'],
    assignedLmoId: 'USR-LMO-002',
    assignedLmoName: 'Smt. Anjali Deshmukh (LMO)',
    assignedGatcId: 'USR-GATC-002',
    assignedGatcName: 'Western India Calibration & Testing Services (GATC)',
    officeAddress: 'Legal Metrology Directorate, Old Custom House, Fort, Mumbai - 400001',
    contactEmail: 'lmo.mumbai@doca.gov.in',
    contactPhone: '+91-22-2266-1088',
  },
  {
    id: 'JUR-KA-BLR-URBAN',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    zone: 'South Zone - Koramangala & Electronic City',
    pinCodes: ['560034', '560095', '560100', '560102'],
    assignedLmoId: 'USR-LMO-003',
    assignedLmoName: 'Shri K. Suresh (LMO)',
    officeAddress: 'Department of Legal Metrology, No. 1, Ali Asker Road, Bengaluru - 560052',
    contactEmail: 'lmo.blr@doca.gov.in',
    contactPhone: '+91-80-2226-5544',
  },
];

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'USR-APP-001',
    fullName: 'Ramesh Kumar',
    email: 'ramesh.kumar@apexretail.in',
    mobile: '+91-98101-23456',
    role: 'APPLICANT',
    businessName: 'Apex Supermarket & Grocery Store',
    businessType: 'RETAIL',
    gstin: '07AAAAA0000A1Z5',
    address: 'Shop No. 14, Main Market, Hauz Khas',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110016',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'USR-APP-002',
    fullName: 'Dr. Priya Sharma',
    email: 'priya.sharma@precisionpharma.com',
    mobile: '+91-98200-98765',
    role: 'APPLICANT',
    businessName: 'Precision Pharma & Diagnostic Labs',
    businessType: 'LABORATORY',
    gstin: '07BBBBA1111B1Z2',
    address: 'Plot 45, Okhla Industrial Area Phase-III',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110020',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  },
  {
    id: 'USR-LMO-001',
    fullName: 'Shri Rajesh Varma',
    email: 'rajesh.varma@doca.gov.in',
    mobile: '+91-98111-54321',
    role: 'LMO',
    designation: 'Senior Legal Metrology Officer (Inspector Grade-I)',
    address: 'Court Complex, Saket',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110017',
    jurisdictionId: 'JUR-DL-SOUTH',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'USR-GATC-001',
    fullName: 'National Metrology Testing Lab',
    email: 'director@natmetrologylab.org',
    mobile: '+91-11-2690-3000',
    role: 'GATC',
    businessName: 'National Metrology Testing Centre Pvt. Ltd.',
    businessType: 'LABORATORY',
    designation: 'Approved Test Centre Director',
    gatcAccreditationNumber: 'DoCA/GATC/2024/042-NORTH',
    gatcValidUntil: '2028-03-31',
    address: 'Technology Park, Okhla Phase-II',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110020',
    jurisdictionId: 'JUR-DL-SOUTH',
    avatarUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=150',
  },
  {
    id: 'USR-ADM-001',
    fullName: 'Director General (Legal Metrology)',
    email: 'admin.metrology@doca.gov.in',
    mobile: '+91-11-2338-6600',
    role: 'ADMIN',
    designation: 'Additional Secretary & Director of Legal Metrology',
    address: 'Krishi Bhawan, Dr. Rajendra Prasad Road',
    district: 'New Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110001',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  },
];

export const MOCK_INSTRUMENTS: Instrument[] = [
  {
    id: 'INST-001',
    ownerId: 'USR-APP-001',
    ownerName: 'Ramesh Kumar',
    businessName: 'Apex Supermarket & Grocery Store',
    category: 'ELECTRONIC_COUNTER_SCALE',
    categoryName: 'Electronic Counter Scale (Commercial)',
    accuracyClass: 'CLASS_III',
    make: 'Essae-Teraoka',
    model: 'DS-215 POS-Scale',
    serialNumber: 'ESS-2024-88412',
    maxCapacity: '30 kg',
    minCapacity: '100 g',
    verificationScaleInterval: '5 g',
    installationAddress: 'Counter 1, Apex Supermarket, Hauz Khas',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110016',
    geoLat: 28.5494,
    geoLng: 77.2001,
    status: 'ACTIVE_VERIFIED',
    lastVerifiedDate: '2025-09-15',
    currentCertificateId: 'CERT-2025-001',
    currentCertificateNumber: 'IND-LM-DL-2025-78210',
    expiryDate: '2026-09-14',
    daysToExpiry: 14,
    createdAt: '2024-09-10',
  },
  {
    id: 'INST-002',
    ownerId: 'USR-APP-001',
    ownerName: 'Ramesh Kumar',
    businessName: 'Apex Supermarket & Grocery Store',
    category: 'PLATFORM_SCALE',
    categoryName: 'Platform Weighing Scale (Bulk Receiving)',
    accuracyClass: 'CLASS_III',
    make: 'Avery Weigh-Tronix',
    model: 'ProPlatform 300',
    serialNumber: 'AVW-2023-45109',
    maxCapacity: '300 kg',
    minCapacity: '1 kg',
    verificationScaleInterval: '50 g',
    installationAddress: 'Loading Bay, Apex Supermarket, Hauz Khas',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110016',
    geoLat: 28.5492,
    geoLng: 77.2005,
    status: 'SCHEDULED',
    createdAt: '2026-08-10',
  },
  {
    id: 'INST-003',
    ownerId: 'USR-APP-002',
    ownerName: 'Dr. Priya Sharma',
    businessName: 'Precision Pharma & Diagnostic Labs',
    category: 'PRECISION_LAB_BALANCE',
    categoryName: 'Analytical Micro-Balance (Laboratory)',
    accuracyClass: 'CLASS_I',
    make: 'Mettler Toledo',
    model: 'XPR-205 Micro-Scale',
    serialNumber: 'MT-2025-99201',
    maxCapacity: '220 g',
    minCapacity: '1 mg',
    verificationScaleInterval: '0.1 mg',
    installationAddress: 'Cleanroom Analytical Lab B-2, Okhla Phase-III',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110020',
    geoLat: 28.5284,
    geoLng: 77.2711,
    status: 'ACTIVE_VERIFIED',
    lastVerifiedDate: '2026-01-10',
    currentCertificateId: 'CERT-2026-002',
    currentCertificateNumber: 'IND-LM-DL-2026-11942',
    expiryDate: '2027-01-09',
    daysToExpiry: 131,
    createdAt: '2025-12-01',
  },
  {
    id: 'INST-004',
    ownerId: 'USR-APP-001',
    ownerName: 'Ramesh Kumar',
    businessName: 'Apex Supermarket & Grocery Store',
    category: 'NON_AUTOMATIC_WEIGHING',
    categoryName: 'Vegetable & Fruit Weighing Scale',
    accuracyClass: 'CLASS_III',
    make: 'Citizen Scale',
    model: 'CZ-30K Price Computing',
    serialNumber: 'CTZ-2022-31092',
    maxCapacity: '15 kg',
    minCapacity: '40 g',
    verificationScaleInterval: '2 g',
    installationAddress: 'Section B, Apex Supermarket, Hauz Khas',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110016',
    geoLat: 28.5496,
    geoLng: 77.2003,
    status: 'DEFICIENT',
    createdAt: '2024-02-14',
  },
  {
    id: 'INST-005',
    ownerId: 'USR-APP-002',
    ownerName: 'Dr. Priya Sharma',
    businessName: 'Precision Pharma & Diagnostic Labs',
    category: 'WEIGHBRIDGE',
    categoryName: 'Heavy Vehicle Weighbridge (Raw Material Dispatch)',
    accuracyClass: 'CLASS_III',
    make: 'Eagle Scales',
    model: 'WB-50T Pitless Weighbridge',
    serialNumber: 'EAG-2023-77140',
    maxCapacity: '50 Tonnes',
    minCapacity: '200 kg',
    verificationScaleInterval: '10 kg',
    installationAddress: 'Main Gate Weigh Station, Okhla Phase-III',
    district: 'South Delhi',
    state: 'Delhi (NCT)',
    pinCode: '110020',
    geoLat: 28.5279,
    geoLng: 77.2725,
    status: 'EXPIRED',
    lastVerifiedDate: '2025-08-01',
    currentCertificateId: 'CERT-2025-005',
    currentCertificateNumber: 'IND-LM-DL-2025-45012',
    expiryDate: '2026-07-31',
    daysToExpiry: -31,
    createdAt: '2024-07-15',
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'APP-2026-001',
    applicationNumber: 'DOCA-APP-2026-9182',
    instrumentId: 'INST-002',
    instrument: MOCK_INSTRUMENTS[1],
    applicantId: 'USR-APP-001',
    applicant: MOCK_USERS[0],
    applicationType: 'INITIAL_VERIFICATION',
    jurisdictionId: 'JUR-DL-SOUTH',
    assignedOfficerId: 'USR-LMO-001',
    assignedOfficerName: 'Shri Rajesh Varma (LMO)',
    assignedOfficerRole: 'LMO',
    assignedAgencyName: 'Department of Legal Metrology, South Delhi',
    status: 'SCHEDULED',
    submittedAt: '2026-08-20T10:30:00Z',
    scheduledDate: '2026-09-02',
    scheduledTimeSlot: '11:00 AM - 01:00 PM',
    feePaidAmount: 500,
    paymentRefNumber: 'PAY-DL-982144',
  },
  {
    id: 'APP-2026-002',
    applicationNumber: 'DOCA-APP-2026-7734',
    instrumentId: 'INST-004',
    instrument: MOCK_INSTRUMENTS[3],
    applicantId: 'USR-APP-001',
    applicant: MOCK_USERS[0],
    applicationType: 'PERIODIC_REVERIFICATION',
    jurisdictionId: 'JUR-DL-SOUTH',
    assignedOfficerId: 'USR-LMO-001',
    assignedOfficerName: 'Shri Rajesh Varma (LMO)',
    assignedOfficerRole: 'LMO',
    status: 'DEFICIENCY_ISSUED',
    submittedAt: '2026-08-15T14:10:00Z',
    completedAt: '2026-08-25T16:00:00Z',
    remarks: 'Error in repeatability test (+8g at 15kg load exceeds MPE of +/-2g). Sealing wire damaged.',
  },
  {
    id: 'APP-2026-003',
    applicationNumber: 'DOCA-APP-2026-5510',
    instrumentId: 'INST-003',
    instrument: MOCK_INSTRUMENTS[2],
    applicantId: 'USR-APP-002',
    applicant: MOCK_USERS[1],
    applicationType: 'PERIODIC_REVERIFICATION',
    jurisdictionId: 'JUR-DL-SOUTH',
    assignedOfficerId: 'USR-GATC-001',
    assignedOfficerName: 'National Metrology Testing Lab (GATC)',
    assignedOfficerRole: 'GATC',
    assignedAgencyName: 'National Metrology Testing Lab (Accredited GATC)',
    status: 'APPROVED',
    submittedAt: '2026-01-05T09:00:00Z',
    completedAt: '2026-01-10T15:30:00Z',
  },
  {
    id: 'APP-2026-004',
    applicationNumber: 'DOCA-APP-2026-3391',
    instrumentId: 'INST-005',
    instrument: MOCK_INSTRUMENTS[4],
    applicantId: 'USR-APP-002',
    applicant: MOCK_USERS[1],
    applicationType: 'PERIODIC_REVERIFICATION',
    jurisdictionId: 'JUR-DL-SOUTH',
    assignedOfficerId: 'USR-LMO-001',
    assignedOfficerName: 'Shri Rajesh Varma (LMO)',
    assignedOfficerRole: 'LMO',
    status: 'SUBMITTED',
    submittedAt: '2026-08-29T11:45:00Z',
    remarks: 'Urgent renewal required - weighbridge certificate expired on 31-July-2026.',
  },
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: 'CERT-2025-001',
    certificateNumber: 'IND-LM-DL-2025-78210',
    applicationId: 'APP-2025-8812',
    applicationNumber: 'DOCA-APP-2025-8812',
    instrumentId: 'INST-001',
    instrument: MOCK_INSTRUMENTS[0],
    ownerId: 'USR-APP-001',
    ownerName: 'Ramesh Kumar',
    businessName: 'Apex Supermarket & Grocery Store',
    issuedByOfficerId: 'USR-LMO-001',
    issuedByOfficerName: 'Shri Rajesh Varma (LMO)',
    issuingAuthority: 'Office of the Assistant Controller, Legal Metrology, South District, Delhi',
    issueDate: '2025-09-15',
    validFrom: '2025-09-15',
    validUntil: '2026-09-14',
    status: 'ACTIVE',
    physicalSealNumber: 'DL-LM-SEAL-88941-K',
    digitalSignatureHash: 'SHA256:7f8ea3b1c4d2e1f083b745e6912ab43c',
    qrPayload: 'https://doca.gov.in/verify/IND-LM-DL-2025-78210',
    verificationUrl: 'https://doca.gov.in/verify/IND-LM-DL-2025-78210',
    statutoryRuleReference: 'Rule 14 of the Legal Metrology (General) Rules, 2011, Schedule IX (Form V)',
  },
  {
    id: 'CERT-2026-002',
    certificateNumber: 'IND-LM-DL-2026-11942',
    applicationId: 'APP-2026-003',
    applicationNumber: 'DOCA-APP-2026-5510',
    instrumentId: 'INST-003',
    instrument: MOCK_INSTRUMENTS[2],
    ownerId: 'USR-APP-002',
    ownerName: 'Dr. Priya Sharma',
    businessName: 'Precision Pharma & Diagnostic Labs',
    issuedByOfficerId: 'USR-GATC-001',
    issuedByOfficerName: 'National Metrology Testing Lab (GATC)',
    issuingAuthority: 'Government Approved Test Centre (GATC No. 042-NORTH) under Directorate of Legal Metrology',
    issueDate: '2026-01-10',
    validFrom: '2026-01-10',
    validUntil: '2027-01-09',
    status: 'ACTIVE',
    physicalSealNumber: 'GATC-042-SEAL-10084',
    digitalSignatureHash: 'SHA256:9981bcfe041d8820c74129bb8893fa11',
    qrPayload: 'https://doca.gov.in/verify/IND-LM-DL-2026-11942',
    verificationUrl: 'https://doca.gov.in/verify/IND-LM-DL-2026-11942',
    statutoryRuleReference: 'Rule 14 of the Legal Metrology (General) Rules, 2011, Schedule IX (Form V)',
  },
  {
    id: 'CERT-2025-005',
    certificateNumber: 'IND-LM-DL-2025-45012',
    applicationId: 'APP-2025-1029',
    applicationNumber: 'DOCA-APP-2025-1029',
    instrumentId: 'INST-005',
    instrument: MOCK_INSTRUMENTS[4],
    ownerId: 'USR-APP-002',
    ownerName: 'Dr. Priya Sharma',
    businessName: 'Precision Pharma & Diagnostic Labs',
    issuedByOfficerId: 'USR-LMO-001',
    issuedByOfficerName: 'Shri Rajesh Varma (LMO)',
    issuingAuthority: 'Office of the Assistant Controller, Legal Metrology, South District, Delhi',
    issueDate: '2025-08-01',
    validFrom: '2025-08-01',
    validUntil: '2026-07-31',
    status: 'EXPIRED',
    physicalSealNumber: 'DL-LM-SEAL-77102-M',
    digitalSignatureHash: 'SHA256:6631ad08f441e938ba113009941efc82',
    qrPayload: 'https://doca.gov.in/verify/IND-LM-DL-2025-45012',
    verificationUrl: 'https://doca.gov.in/verify/IND-LM-DL-2025-45012',
    statutoryRuleReference: 'Rule 14 of the Legal Metrology (General) Rules, 2011, Schedule IX (Form V)',
  },
];

export const MOCK_DEFICIENCY_MEMOS: DeficiencyMemo[] = [
  {
    id: 'DEF-2026-001',
    memoNumber: 'DOCA-DEF-2026-1049',
    applicationId: 'APP-2026-002',
    applicationNumber: 'DOCA-APP-2026-7734',
    instrumentId: 'INST-004',
    instrumentName: 'Vegetable & Fruit Weighing Scale (Citizen Scale CZ-30K)',
    ownerId: 'USR-APP-001',
    ownerName: 'Ramesh Kumar',
    businessName: 'Apex Supermarket & Grocery Store',
    officerId: 'USR-LMO-001',
    officerName: 'Shri Rajesh Varma (LMO)',
    issuedDate: '2026-08-25',
    cureDeadline: '2026-09-08',
    reasons: [
      'Maximum Permissible Error (MPE) exceeded during full capacity load test (+8g vs MPE limit +/-2g).',
      'Tamper-evident lead seal wire broken/missing on the lower calibration adjustment housing.',
      'Display digit segment flickering on unit price display.',
    ],
    observedDiscrepancy: 'Instrument shows systematic positive bias (+8 grams on 15kg certified test weight). Non-compliant with Legal Metrology General Rules 2011 Seventh Schedule.',
    requiredRectification: '1. Recalibration by a registered Legal Metrology Repairer. 2. Repair of display unit. 3. Resubmit proof of repair for re-inspection stamping within 14 calendar days.',
    status: 'OPEN',
  },
];

export const MOCK_RENEWAL_ALERTS: RenewalAlert[] = [
  {
    id: 'ALERT-001',
    instrumentId: 'INST-001',
    instrumentName: 'Electronic Counter Scale (Essae DS-215)',
    ownerId: 'USR-APP-001',
    certificateNumber: 'IND-LM-DL-2025-78210',
    expiryDate: '2026-09-14',
    daysRemaining: 14,
    alertType: '30_DAYS',
    sentAt: '2026-08-15T09:00:00Z',
    status: 'SEEN',
  },
  {
    id: 'ALERT-002',
    instrumentId: 'INST-005',
    instrumentName: 'Heavy Vehicle Weighbridge (50 Tonnes)',
    ownerId: 'USR-APP-002',
    certificateNumber: 'IND-LM-DL-2025-45012',
    expiryDate: '2026-07-31',
    daysRemaining: -31,
    alertType: 'EXPIRED',
    sentAt: '2026-08-01T08:00:00Z',
    status: 'SEEN',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'LOG-001',
    timestamp: '2026-08-29T11:45:00Z',
    actorId: 'USR-APP-002',
    actorName: 'Dr. Priya Sharma',
    actorRole: 'APPLICANT',
    action: 'APPLICATION_SUBMITTED',
    entityType: 'APPLICATION',
    entityId: 'APP-2026-004',
    details: 'Submitted re-verification application for 50T Weighbridge (EAG-2023-77140)',
    ipAddress: '103.21.144.92',
  },
  {
    id: 'LOG-002',
    timestamp: '2026-08-25T16:00:00Z',
    actorId: 'USR-LMO-001',
    actorName: 'Shri Rajesh Varma (LMO)',
    actorRole: 'LMO',
    action: 'DEFICIENCY_ISSUED',
    entityType: 'DEFICIENCY_MEMO',
    entityId: 'DOCA-DEF-2026-1049',
    details: 'Issued deficiency memo DOCA-DEF-2026-1049 for failed calibration and broken seal',
    ipAddress: '164.100.24.11',
  },
  {
    id: 'LOG-003',
    timestamp: '2026-08-20T10:30:00Z',
    actorId: 'USR-LMO-001',
    actorName: 'Shri Rajesh Varma (LMO)',
    actorRole: 'LMO',
    action: 'SCHEDULED',
    entityType: 'APPLICATION',
    entityId: 'APP-2026-001',
    details: 'Scheduled field inspection for Platform Scale on 02-Sep-2026 (11:00 AM)',
    ipAddress: '164.100.24.11',
  },
  {
    id: 'LOG-004',
    timestamp: '2026-01-10T15:30:00Z',
    actorId: 'USR-GATC-001',
    actorName: 'National Metrology Testing Lab (GATC)',
    actorRole: 'GATC',
    action: 'CERTIFICATE_ISSUED',
    entityType: 'CERTIFICATE',
    entityId: 'CERT-2026-002',
    details: 'Issued digital certificate IND-LM-DL-2026-11942 with cryptographic QR code',
    ipAddress: '115.112.80.3',
  },
];
